services:
  my_service:
    build:
      context: .
      dockerfile: Dockerfile.train
    env_file:
      - train.env
    command: ["python3", "main.py"]
    deploy:
      resources:
        limits:
          memory: "16g"
    ipc: host
    ulimits:
      memlock:
        soft: -1
        hard: -1
      stack:
        soft: 67108864
        hard: 67108864
    network_mode: host
    volumes:
          # local_path:/path/inside/container
          - ./optimare_slices_3200_480:/train/optimare_slices_3200_480
