repos:
    - repo: https://github.com/Lucas-C/pre-commit-hooks
      rev: v1.5.5
      hooks:
          - id: forbid-crlf
          - id: remove-crlf
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.4.0
      hooks:
          - id: trailing-whitespace
          - id: check-added-large-files
          - id: end-of-file-fixer
            types: [text]
          - id: check-yaml
            types: [yaml]
          - id: check-toml
            types: [toml]
    - repo: https://github.com/ambv/black
      rev: 24.8.0
      hooks:
          - id: black
            language_version: python3.10
    - repo: https://github.com/pycqa/flake8
      rev: 7.1.1
      hooks:
          - id: flake8
    # - repo: https://github.com/pre-commit/mirrors-mypy
    #   rev: v1.11.2
    #   hooks:
    #       - id: mypy
    #         exclude: tests/
